export const tools = [
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Prettify and validate JSON with syntax highlighting",
    category: "JSON",
    icon: ["fas", "file-code"],
    path: "/tools/json-formatter",
    component: () => import("./json/JsonFormatter"),
    keywords: ["json", "format", "prettify", "beautify", "validate"],
  },
  {
    id: "json-minifier",
    name: "JSON Minifier",
    description: "Remove whitespace from JSON for compact output",
    category: "JSON",
    icon: ["fas", "compress"],
    path: "/tools/json-minifier",
    component: () => import("./json/JsonMinifier"),
    keywords: ["json", "minify", "compress", "compact"],
  },
  {
    id: "json-yaml",
    name: "JSON ↔ YAML Converter",
    description: "Convert between JSON and YAML formats",
    category: "JSON",
    icon: ["fas", "exchange-alt"],
    path: "/tools/json-yaml",
    component: () => import("./json/JsonYamlConverter"),
    keywords: ["json", "yaml", "convert", "transform"],
  },
  {
    id: "xml-formatter",
    name: "XML Formatter",
    description: "Prettify and validate XML with proper indentation",
    category: "XML",
    icon: ["fas", "code"],
    path: "/tools/xml-formatter",
    component: () => import("./xml/XmlFormatter"),
    keywords: ["xml", "format", "prettify", "beautify", "validate"],
  },
  {
    id: "xml-minifier",
    name: "XML Minifier",
    description: "Strip whitespace from XML for compact output",
    category: "XML",
    icon: ["fas", "compress"],
    path: "/tools/xml-minifier",
    component: () => import("./xml/XmlMinifier"),
    keywords: ["xml", "minify", "compress", "compact"],
  },
  {
    id: "base64-encoder-decoder",
    name: "Base64 Encoder/Decoder",
    description: "Encode text to Base64 or decode Base64 back to text",
    category: "Text",
    icon: ["fas", "exchange-alt"],
    path: "/tools/base64-encoder-decoder",
    component: () => import("./text/Base64EncoderDecoder"),
    keywords: ["base64", "encode", "decode", "text", "binary"],
  },
  {
    id: "url-encoder-decoder",
    name: "URL Encoder/Decoder",
    description: "Encode URLs for safe transmission or decode encoded URLs",
    category: "Text",
    icon: ["fas", "link"],
    path: "/tools/url-encoder-decoder",
    component: () => import("./text/UrlEncoderDecoder"),
    keywords: ["url", "encode", "decode", "uri", "percent"],
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and more in your text",
    category: "Text",
    icon: ["fas", "calculator"],
    path: "/tools/word-counter",
    component: () => import("./text/WordCounter"),
    keywords: ["word", "count", "character", "sentence", "paragraph", "stats"],
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert text between different case formats",
    category: "Text",
    icon: ["fas", "font"],
    path: "/tools/case-converter",
    component: () => import("./text/CaseConverter"),
    keywords: ["case", "convert", "uppercase", "lowercase", "camelcase", "snake"],
  },
  {
    id: "duplicate-finder",
    name: "Duplicate Finder",
    description: "Find duplicate items in a comma or newline separated list",
    category: "Text",
    icon: ["fas", "clone"],
    path: "/tools/duplicate-finder",
    component: () => import("./text/DuplicateFinder"),
    keywords: ["duplicate", "find", "list", "unique", "repeat", "distinct"],
  },
  {
    id: "multiline-to-list",
    name: "Multiline to List",
    description: "Convert multiline text to a comma-separated list",
    category: "Text",
    icon: ["fas", "list"],
    path: "/tools/multiline-to-list",
    component: () => import("./text/MultilineToList"),
    keywords: ["multiline", "comma", "list", "csv", "separator", "join"],
  },
  {
    id: "image-to-text",
    name: "Image to Text (OCR)",
    description: "Extract text from images using OCR technology powered by Tesseract.js",
    category: "Image",
    icon: ["fas", "image"],
    path: "/tools/image-to-text",
    component: () => import("./image/ImageToText"),
    keywords: ["image", "text", "ocr", "extract", "tesseract", "scan"],
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates",
    category: "Misc",
    icon: ["fas", "clock"],
    path: "/tools/timestamp-converter",
    component: () => import("./misc/TimestampConverter"),
    keywords: ["timestamp", "date", "time", "unix", "convert"],
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUID v4 identifiers",
    category: "Misc",
    icon: ["fas", "fingerprint"],
    path: "/tools/uuid-generator",
    component: () => import("./misc/UuidGenerator"),
    keywords: ["uuid", "guid", "identifier", "random", "generate"],
  },
  {
    id: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, and HSL formats",
    category: "Misc",
    icon: ["fas", "palette"],
    path: "/tools/color-converter",
    component: () => import("./misc/ColorConverter"),
    keywords: ["color", "hex", "rgb", "hsl", "convert"],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test and validate regular expressions with live matching",
    category: "Misc",
    icon: ["fas", "search"],
    path: "/tools/regex-tester",
    component: () => import("./misc/RegexTester"),
    keywords: ["regex", "regexp", "pattern", "match", "test"],
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode JSON Web Tokens to view header and payload",
    category: "Misc",
    icon: ["fas", "key"],
    path: "/tools/jwt-decoder",
    component: () => import("./misc/JwtDecoder"),
    keywords: ["jwt", "token", "decode", "auth", "header", "payload"],
  },
]

export const categories = ["JSON", "XML", "Text", "Image", "Misc"]
